### ISSUE TITLE
ImportError: No module named 'requests'

### ISSUE THREAD

**Issue by paradonym** [wichmannpas/uberspace-downtime-notify#3]
issue:
```
[$USER@alkaid ~]$ /usr/local/bin/python3 $HOME/uberspace-downtime-notify/fetch.py
Traceback (most recent call last):
  File "/home/$USER/uberspace-downtime-notify/fetch.py", line 14, in <module>
    import requests
ImportError: No module named 'requests'
[$USER@alkaid ~]$ pip3.6 install requests --user
Collecting requests
  Downloading requests-2.18.4-py2.py3-none-any.whl (88kB)
    100% |████████████████████████████████| 92kB 4.6MB/s
Collecting certifi>=2017.4.17 (from requests)
  Downloading certifi-2017.7.27.1-py2.py3-none-any.whl (349kB)
    100% |████████████████████████████████| 358kB 2.2MB/s
Collecting chardet<3.1.0,>=3.0.2 (from requests)
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 5.2MB/s
Collecting idna<2.7,>=2.5 (from requests)
  Downloading idna-2.6-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 7.3MB/s
Collecting urllib3<1.23,>=1.21.1 (from requests)
  Downloading urllib3-1.22-py2.py3-none-any.whl (132kB)
    100% |████████████████████████████████| 133kB 5.3MB/s
Installing collected packages: certifi, chardet, idna, urllib3, requests
Successfully installed certifi-2017.7.27.1 chardet-3.0.4 idna-2.6 requests-2.18.4 urllib3-1.22
[$USER@alkaid ~]$ /usr/local/bin/python3 $HOME/uberspace-downtime-notify/fetch.py
Traceback (most recent call last):
  File "/home/$USER/uberspace-downtime-notify/fetch.py", line 14, in <module>
    import requests
ImportError: No module named 'requests'
```

research:
https://stackoverflow.com/questions/17309288/importerror-no-module-named-requests It seems that the module isn't installed on my uberspace.

https://wiki.uberspace.de/development:python - therefore executed `pip3.6 install requests --user` as python3 is used.

Did I missed something when installing requests?

**Comment by wichmannpas** [comment]
Are you using the same PyPI version as Python? In your code block, you are using pip3.6; `/usr/local/bin/python3` seems to be a Python 3.4.6 on Uberspace hosts.
Try replacing `/usr/local/bin/python3` in the invocation by `/usr/local/bin/python3.6` or otherwise installing the requirements using pip3.4.

An additional note, to install all requirements of a Python project (though it does not matter for this one as requests is the only requirement), you could use `pip install -r requirements.txt`.

As not all Uberspace hosts seem to have the requests package installed system-wide (alpheca has), it would be good to update the README to cover the installation of the requirements. I would appreciate a pull request if your issue should be solved by the solution mentioned above.
